server:
 port: 80
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ssm_db?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123